### create coach
POST http://localhost:3000/tecnico/create-coach
Content-Type: application/json

{
    "nombre":"melliso"
}

### get coach
GET http://localhost:3000/tecnico/get-coach

### get coach
GET http://localhost:3000/tecnico/get-coach?playerData=YES