### create player
POST http://localhost:3000/jugador/create-player
Content-Type: application/json

{
    "nombre":"messi"
}

### get player
GET http://localhost:3000/jugador/get-player?playerId=65c181c747ba8175b57c53d

### prom - player
PATCH  http://localhost:3000/jugador/promotion-player
Content-Type: application/json

{
    "playerId":"65bd09228782778af1482439",
    "estrellas": 2
}