### create player
POST http://localhost:3000/jugador/create-player
Content-Type: application/json

{
    "nombre":"ronaldo",
    "valor":300
}

### get player
GET http://localhost:3000/jugador/get-player

### prom - player
PATCH  http://localhost:3000/jugador/promotion-player
Content-Type: application/json

{
    "playerId":"65bd09228782778af1482439",
    "estrellas": 2
}